services:
  swtp-server:
    build: 
      context: ./
      dockerfile: ./Server/Dockerfile
    image: swtp-server-img
    restart: always
    container_name: swtp-server
    environment:
      - HOST_OF_API=swtp-server
      - FAST_API_PORT=8000
      - SOCKET_SERVER_PORT=12345
      - NETWORK=swtp-net
    ports:
      - "12345:12345"
      - "8000:8000"
    networks:
      - swtp-net
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
  
  swtp-game-client:
    build: 
      context: ./
      dockerfile: ./GameClient/Dockerfile
    image: game-client-img
    networks:
      - swtp-net
    depends_on:
      - swtp-server

  swtp-frontend:
    build:
      context: ./
      dockerfile: ./Frontend/Dockerfile
    image: frontend-img
    restart: always
    container_name: swtp-frontend
    networks:
      - swtp-net
    depends_on:
      - swtp-server
    ports:
      - "8080:8080"

networks:
  swtp-net:
    name: swtp-net
