services:
  swtp-server:
    build: 
      context: ./
      dockerfile: ./Server/Dockerfile
    image: swtp-server-img
    restart: always
    container_name: swtp-server
    environment:
      -  PORT_TO_GAME_CLIENT=12345
      -  FAST_API_PORT=8000
      -  HOST_SOCKET_SERVER=swtp-server
      -  HOST_FAST_API=swtp-server
      -  NETWORK=swpt-net
    ports:
      - "12345:12345"
      - "8000:8000"
    networks:
      - swpt-net
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
  
  swtp-game-client:
    build: 
      context: ./
      dockerfile: ./GameClient/Dockerfile
    image: game-client-img
    environment:
      - PORT_TO_GAME_CLIENT=12345
      - HOST_SOCKET_SERVER=swtp-server
      - LOBBY_KEY=MISSING_LOBBY_KEY
    networks:
      - swpt-net
    expose:
      - "12345"
    depends_on:
      - swtp-server

    

networks:
  swpt-net:
    name: swtp-net

  


  