services:
  swtp-server:
    build:
      context: ./
      dockerfile: ./Server/Dockerfile
    image: swtp-server-img
    container_name: swtp-server
    environment:
      - SERVER_HOST=swtp-server
      - SERVER_PORT=8010
      - NETWORK=swtp-net
      - WORKER=1
      - PODMAN_HOST=unix:///run/podman/podman.sock
    ports:
      - "8010:8010"
    networks:
      - swtp-net
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '0'

  swtp-game-client:
    build:
      context: ./
      dockerfile: ./GameClient/Dockerfile
    image: game-client-img
    networks:
      - swtp-net
    depends_on:
      - swtp-server

  swtp-frontend:
    build:
      context: ./
      dockerfile: ./Frontend/Dockerfile
    image: frontend-img
    restart: always
    container_name: swtp-frontend
    networks:
      - swtp-net
    depends_on:
      - swtp-server
    ports:
      - "8086:8080"
  
  swtp-frontend-debug:
    build:
      context: ./
      dockerfile: ./FrontendDebug/Dockerfile
    image: frontend-debug-img
    restart: always
    container_name: swtp-frontend-debug
    networks:
      - swtp-net
    depends_on:
      - swtp-server
    ports:
      - "8087:8080"

  swtp-test:
    build: ./Test
    image: swtp-test
    container_name: swtp-test
    networks:
      - swtp-net
    depends_on:
      - swtp-server

networks:
  swtp-net:
    name: swtp-net