services:
  swtp-server:
    build:
      context: ./
      dockerfile: ./Server/Dockerfile
    image: swtp-server-img
    container_name: swtp-server
    environment:
      - SERVER_HOST=swtp-server
      - SERVER_PORT=8000
      - NETWORK=swtp-net
    ports:
      - "8000:8000"
    networks:
      - swtp-net
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock

  swtp-game-client:
    build:
      context: ./
      dockerfile: ./GameClient/Dockerfile
    image: game-client-img
    networks:
      - swtp-net
    depends_on:
      - swtp-server

  swtp-frontend:
    build:
      context: ./
      dockerfile: ./Frontend/Dockerfile
    image: frontend-img
    restart: always
    container_name: swtp-frontend
    networks:
      - swtp-net
    depends_on:
      - swtp-server
    ports:
      - "8085:8080"

networks:
  swtp-net:
    name: swtp-net